# Generated by Django 5.2.7 on 2025-11-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(help_text='Insira a data no formato dd-mm-aaaa', verbose_name='Data de Nascimento')),
                ('horario_visita', models.DateTimeField(auto_now_add=True, verbose_name='Horário de Visita no Site')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail de contato')),
                ('nota', models.CharField(choices=[('5', '5 - Bom'), ('6', '6 - Muito Bom'), ('7', '7 - Ótimo'), ('8', '8 - Excelente'), ('9', '9 - Maravilhoso'), ('10', '10 - Perfeito')], default='10', max_length=10, verbose_name='Deixe sua avaliação sobre o site')),
                ('comentario', models.TextField(blank=True, max_length=500, null=True, verbose_name='Deixe seu comentário')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
            },
        ),
    ]
